Fix/front wordsel adding
ASHIJANKEN/JapaneseWordSeparator pull request #9
Opened 2020-04-10 06:38 UTC by woodmix

調子に乗ってもう一つ。githubの操作、あんまり自信ないので、プルリクの仕方これであってるか分からないですけど。
既存のキャレットがあるときに、それより前方を ctrl+ダブルクリック したときも単語選択が機能するようにしました。

2020-06-06 08:32 UTC, ASHIJANKEN commented
今コードを見ていますが、その前に二つコメントです。

- [#8](https://github.com/ASHIJANKEN/JapaneseWordSeparator/pull/8)のコミットがこのプルリクにも入ってしまっています。[9ecb736](https://github.com/ASHIJANKEN/JapaneseWordSeparator/pull/8/commits/9ecb736d7b11ec3a85190e401eac1ab674b5401f)のブランチ上にこのコミットをつなげるのではなく、ASHIJANKEN:masterから新しくブランチを切って、その上にこのコミットを持ってきてください。
- l.67にprint文が残っているので、できるだけ負荷を減らすために、コメントアウトするか削除するかしてください。

2020-06-06 10:01 UTC, ASHIJANKEN commented
確かに前方を ctrl+ダブルクリック したときも単語選択が機能するようになっているようです。

しかし、現状のコードでは、同時に最後方の選択範囲が消えてしまうバグが残っているようです(キャレットだけ残っています)。

2020-06-06 13:43 UTC, ASHIJANKEN requested changes

2020-06-06 13:43 UTC, ASHIJANKEN commented on japanesewordseparator.py
> +    if(firepoint is None):
この条件文にカッコは必要ない(つけてもつけなくても挙動が変わらない)と思うので、外してください。
他のif文とのスタイルを合わせたい、という意図もあります。

2020-06-06 13:43 UTC, ASHIJANKEN commented on japanesewordseparator.py
> +    if(command_name == "drag_select_jp"):
ここもです。

2020-06-06 13:43 UTC, ASHIJANKEN commented on japanesewordseparator.py
> +      print("firepoint is None! what's up?")
できるだけ動作時の負荷を減らすために、コメントアウトするか削除するかしてください。(本当はdebug用のプリント文はないのが理想です。が、僕もコメントで残してしまっているので...)

2020-06-06 14:08 UTC, ASHIJANKEN commented
コードを一通り見ました。
いくつか形式的なものに関してコメントを付けましたので、ご確認ください。

確かに前方を ctrl+ダブルクリック したときも単語選択が機能するようになっているようです。
僕もself.view.sel()[-1].bに問題があると認識していたので、直してくれてありがとうございます。

ただ、現状のコードでは、同時に後方の選択範囲が消えてしまうバグが残っているようです。キャレットも残ったり消えたりします。

2020-06-08 01:19 UTC, woodmix commented
あー、たしかにドラッグした時の挙動がなんか変ですね。ダブルクリックした瞬間の挙動しか見てなかった…
すいません。このプルリクはいったんキャンセルさせてください。

2020-08-11 17:53 UTC, merged

2020-08-11 18:03 UTC, ASHIJANKEN commented
バグは私が書いたコードにありました。
ということで、いろいろfixしたのでマージします。
(マージの処理がうまくいかなくて、余分なコミットがいくつかできてしまいました...)